### ISSUE TITLE
community guidelines: where to seek support

### ISSUE THREAD

**Issue by tukss** [AMReX-Astro/MAESTROeX#106]
This is a issue related to the JOSS submission: openjournals/joss-reviews#1757

There are clear instructions on how to contribute though pull requests both in the README file and the documentation. This is good.

The README file mentions a mailing list as the place to get help. When I follow the [link](https://groups.google.com/forum/#!forum/maestro-help), I just get a message that the group doesn't exist or I don't have permission to access it. If the group is indeed private, there should be information on how to get invited.

There is no explicit information on how to report issues. You might want to indicate your preference on using GitHub's issue tracker or sending emails in the README.

**Comment by harpolea** [comment]
I've changed the `Getting Help` section of the README in 0eb8340 so it now directs users to the FAQ section of the User's Guide and asks them to submit a github issue if they require further assistance or wish to report a bug

**Comment by harpolea** [comment]
It turns out the visibility of the mailing list group was incorrect, so now that's been fixed I've added it back to the README

**Comment by tukss** [comment]
Great. That looks good to me.
