### ISSUE TITLE
[JOSS] improvements for Paper

### ISSUE THREAD

**Issue by tukss** [AMReX-Astro/MAESTROeX#107]
This is part of the review of the JOSS paper, which is part of this repository.
openjournals/joss-reviews#1757

The paper is mostly fine, but I have a few points for improvement to meet the checklist for the review.
- Fan et al. (2019) has been submitted to ApJ, but is already on the arXiv. Can you add a link to the [arXiv submission](https://arxiv.org/abs/1908.03634) to the bibliography?
- To accurately describe what the target audience is, can you add a statement on the range of applicability? For example: The algorithm becomes inaccurate above Mach numbers of …
- JOSS asks for a description of the state of the field. Can you briefly describe how the MAESTROeX approach compares to other commonly used hydro schemes? For example, fully compressible or anelastic.

**Comment by pgrete** [comment]
I agree with with these recommendations.
Moreover, with respect to the third item it'd also be good to refer to a few comparable codes that also implement low Mach number schemes (from the guide: _A list of key references, including to other software addressing related needs._)

**Comment by ajnonaka** [comment]
Addressed in fbf9db7b0b5ccbf085d7b9d7a47783b16c67f484.  For comparison to other low Mach schemes (point #3), I instead added a reference to the MAESTROeX paper where it is discussed more thoroughly.
