### ISSUE TITLE
[JOSS] Issue/problem reporting

### ISSUE THREAD

**Issue by pgrete** [AMReX-Astro/MAESTROeX#109]
I currently cannot find instructions on the process of reporting issues and/or problems (beyond asking for help on the mailing list).
It'd be good to have that info already in the README and optimal (but not necessary) to have a template.

linking issue: https://github.com/openjournals/joss-reviews/issues/1757

**Comment by harpolea** [comment]
If you check out the development branch, I added instructions in the README that direct users to the User's Guide FAQ and invite them to submit GitHub issues if they discover any bugs.

**Comment by ajnonaka** [comment]
I also added a note about submitting an issue on github to the gh-pages front page (it already directed to the User's Guide and the mailing list)
