### ISSUE TITLE
[JOSS] Development model documention

### ISSUE THREAD

**Issue by pgrete** [AMReX-Astro/MAESTROeX#110]
The documentation https://amrex-astro.github.io/MAESTROeX/docs/getting_started.html#development-model does not mention the requirement of using a fork (as does the README).
Moreover, it'd be great (but not necessary) to provide a template for pull requests -- especially as it would make the resulting squashed message more accessible to new users and more streamlined in general.

linking issue: openjournals/joss-reviews#1757

**Comment by pgrete** [comment]
This also applies to the "Development" section on the homepage: https://amrex-astro.github.io/MAESTROeX/

**Comment by harpolea** [comment]
I've updated the User's Guide (115f582f27) and the home page (646058f) to instruct users to submit a PR from their fork.

**Comment by pgrete** [comment]
For the purpose of the JOSS review this issue may be closed.
However, feel free to keep it open as a reminder in case you consider adding pull request and/or issue templates.
