### ISSUE TITLE
[JOSS] Author list

### ISSUE THREAD

**Issue by pgrete** [AMReX-Astro/MAESTROeX#114]
Why is the author list in the software paper dissimilar from the authorlist on the homepage https://amrex-astro.github.io/MAESTROeX/who.html ?

linking issue: openjournals/joss-reviews#1757

**Comment by harpolea** [comment]
The author list on the website also includes developers of the previous MAESTRO code, whereas the author list on the paper only lists developers of the new MAESTROeX code.

**Comment by ajnonaka** [comment]
Wondering if we should put a note in the acknowledgements section of the JOSS paper those who were involved with original MAESTRO algorithm+software development.

**Comment by ajnonaka** [comment]
OK this is done now in the development branch b8b31a6e483377fcb92a318b50b2541177f2911e
