### ISSUE TITLE
[JOSS] Plotting instructions are out of date

### ISSUE THREAD

**Issue by pgrete** [AMReX-Astro/MAESTROeX#115]
I tried to follow https://amrex-astro.github.io/MAESTROeX/docs/visualization.html#python-visualization-scripts and the AMReX structure probably changed.
I found the fsnapshot tool in `amrex/Tools/Plotfile`.

Also the `yt` example that are supposed to be in the `Util` folder are missing.

linking issue: openjournals/joss-reviews#1757

**Comment by harpolea** [comment]
I've updated the plotting instructions in the docs and put the required scripts in the `Util/yt` directory
