### ISSUE TITLE
reacting_bubble 2-d with AMR crashes when run with both MPI and OpenMP

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/MAESTROeX#116]
Run the `reacting_bubble` test with the `inputs_2d_regression.2levels` inputs file, using both MPI and OpenMP and we get segfaults.

**Comment by harpolea** [comment]
I get the error 
`0x563bb349d805 _ZN7Maestro8ErrorEstEiRN5amrex11TagBoxArrayEdi._omp_fn.1
	../../../Source/MaestroRegrid.cpp:257
`
which suggests it's having problems with this line https://github.com/AMReX-Astro/MAESTROeX/blob/eb162a49f27caed803e604ef1cd67ab6e8cd1071/Source/MaestroRegrid.cpp#L257

**Comment by zingale** [comment]
I get:
```
Assertion failed in file src/mpid/ch3/src/ch3u_request.c at line 649: MPIU_Object_get_ref((req)) >= 0
```
when run in DEBUG mode.

**Comment by ajnonaka** [comment]
I think I found the issue.  The OMP region should be isolated to the MFIter loop to retag the boxes after collecting tag_array.  I also think OMP should NOT be used in the original tagging, as it creates a race condition when writing to tag_array.  Testing now.

**Comment by ajnonaka** [comment]
Well the problem runs now with MPI+OpenMP and planar - I unfortunately had to turn off OpenMP for the tagging altogether (so spherical doesn't have it at the moment; easy enough to add in with an "if" statement if needed).  Something is funny with how tag_array works in planar I don't understand yet.
