### ISSUE TITLE
burner integration fails with SDC

### ISSUE THREAD

**Issue by harpolea** [AMReX-Astro/MAESTROeX#124]
I've tried running the `reacting_bubble` and `flame` problems compiled with MPI and SDC, and both produce the error `ERROR in burner: integration failed !!!` when trying to generate the plotfile data. I don't see this error without SDC.

**Comment by ajnonaka** [comment]
Don's pull request #223 to Microphysics allows the problem to run and give sensible results, but omegadot in the plotfiles doesn't look correct for all variables.  Try inputs_2d_C in reacting_bubble with SDC and it shows omegadot(Mg)=0 in the plotfile.

**Comment by zingale** [comment]
SDC has been removed
