### ISSUE TITLE
Multilevel 3d reacting bubble is non-deterministic with OMP and with GPU

### ISSUE THREAD

**Issue by harpolea** [AMReX-Astro/MAESTROeX#149]
The 3d reacting bubble test with multiple levels of refinement is non-deterministic if run with OMP. This has been the case since at least the November release (1d7e89365379eea57680f738f271c93d7f28e513), so this bug has not been introduced in recent changes.

**Comment by ajnonaka** [comment]
I've been able to isolate the problem to the single MFIter loop in MaestroMakeUtrans.cpp - turning tiling off seems to fix the problem but I can't explain why.

**Comment by harpolea** [comment]
The OMP non-determinism is fixed by #150, however it is still non-deterministic on GPU.
