### ISSUE TITLE
make MIcrophysics a submodule

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/MAESTROeX#163]
We should get rid of the MAESTROeX-specific Microphysics/ directory and instead put StarKiller Microphysics as a git submodule, just like we did with Castro.

This will reduce code maintainence.

**Comment by adam-m-jcbs** [comment]
I would like to help with this (or lead it myself), but should know if there's a deadline this would be good to have done by.

**Comment by zingale** [comment]
this was done in #166
