### ISSUE TITLE
Commit to AMReX Broke MAESTROeX

### ISSUE THREAD

**Issue by ajnonaka** [AMReX-Astro/MAESTROeX#20]
Currently wdconvect with inputs_3d_regression fails during the first MAC projection (too many multigrid V-cycles).  (pure MPI)

If I back out amrex to 953c10b3c07a914973aea6e8c6bad69b9cbcd88d the wdconvect example runs correctly.  No further time to debug it at the moment.

**Comment by zingale** [comment]
maybe this should be posed to AMReX?

**Comment by ajnonaka** [comment]
I'll post to AMReX.

It was one of the 2 most recent commits to AMReX that breaks MAESTROeX:

commit ce5d30d09d090be5bbc280bfa681262693e5ef2d (HEAD -> development, origin/development)
Merge: 87e055c7a 92174343a
Author: sireeveslbl <sireeves@lbl.gov>
Date:   Thu Oct 4 15:17:57 2018 -0700

    Merge branch 'development' of https://github.com/AMReX-Codes/amrex into development

commit 92174343a3a59c3cdf36d4d2291bb2d72639ef6f
Merge: e4c681c65 953c10b3c
Author: Andrew Myers <atmyers@lbl.gov>
Date:   Thu Oct 4 16:49:03 2018 -0400

    Merge branch 'development' of github.com:AMReX-Codes/amrex into development

**Comment by ajnonaka** [comment]
Put a more elaborate post in AMReX.  Going offline now for a few hours.

**Comment by ajnonaka** [comment]
AMReX updated; there was some code that was subtracting off averages of RHS's that was being applied to wdconvect (which has outflow, so it shouldn't be used)
