### ISSUE TITLE
Flame with AMR

### ISSUE THREAD

**Issue by ChrisDeGrendele** [AMReX-Astro/MAESTROeX#204]
`MAESTROeX/Exec/science/flame` when run with AMR gives:

```
Erroneous arithmetic operation
```
To reproduce: 
Compile flame setup as is with the current main branch: `make`
Run with: `./Maestro2d.gnu.MPI.ex inputs_2d_smallscale amr.max_level=1`

**Comment by ChrisDeGrendele** [comment]
This isn't fixed with PR #212, it still presents the same error.

**Comment by ajnonaka** [comment]
#214 fixed an issue with defining the end radial coordinate when refining to the top of the domain.

If you change the tagging so we tag to the top of the domain (instead of a strip), optimized builds crash in cellconslin_slopes_mclim at the outflow/periodic corner at the top of the domain.

**Comment by ChrisDeGrendele** [comment]
Fixed by #215 we were wrongly defining where ghost cells began causing a failure when FillPatch tried to fill the external boundaries.
