### ISSUE TITLE
Flame sdc blows up

### ISSUE THREAD

**Issue by ChrisDeGrendele** [AMReX-Astro/MAESTROeX#205]
`MAESTROeX/Exec/science/flame` when run with SDC blows up. The flame propagates for a bit, then the entire domain seems to ignite at once.

To reproduce: 
Compile flame setup as is with the current main branch: `make`
Run with: `./Maestro2d.gnu.MPI.ex inputs_2d_smallscale_sdc`

**Comment by ajnonaka** [comment]
First, make sure you build with USE_SDC=TRUE.  Then the string "SDC" will appear in the exectuable.
If I compare inputs_2d_smallscale and inputs_2d_smallscale_sdc there are a few small differences:
enthalpy_pred_type differs
use_tfromp differs
I think the debugging should begin with inputs_2d_smallscale but with a USE_SDC=TRUE executable.  In other words, I am looking into an SDC run with enthalyp_pred_type=1 and use_tfromp=false.

**Comment by ajnonaka** [comment]
Update: inputs_2d_smallscale does work with SDC.  Trying to figure out if it's the enthalpy_pred_type and/or the use_tfromp/dpdt_factor that causes the problem to break.

**Comment by ajnonaka** [comment]
This can be closed upon merging of #206

**Comment by ajnonaka** [comment]
Fixed with PR #206
