### ISSUE TITLE
SDC with AMR for Flame

### ISSUE THREAD

**Issue by ChrisDeGrendele** [AMReX-Astro/MAESTROeX#220]
Seems to always fails on the 19th timestep (except for in debug mode), but seems to fail slightly differently depending on how many nodes/processes are given. This could be expected but confused me for a while, because on cori I was getting the erroneous arithmetic operation, but locally I could only obtain a MLMG failure. So I've included a couple reproduces:

To reproduce use current development branch of `flame`.
 * `make -j USE_SDC=TRUE`
 * `mpiexec -n 16 ./Maestro2d.gnu.MPI.SDC.ex inputs_2d_smallscale_sdc amr.max_level=1 maestro.eps_init_proj_cart = 1.e-9`
* Failure: MLMG Failed to converge

With 1: (takes a while to get to 19th timestep)
* ./Maestro2d.gnu.MPI.SDC.ex inputs_2d_smallscale_sdc amr.max_level=1 maestro.eps_init_proj_cart = 1.e-9
* Failure: Erroneous arithmetic operation

With 32:
* `mpiexec -n 32 ./Maestro2d.gnu.MPI.SDC.ex inputs_2d_smallscale_sdc amr.max_level=1 maestro.eps_init_proj_cart = 1.e-9`
* Failure: amrex::Error::5::ERROR in burner: integration failed !!!
SIGABRT
Erroneous arithmetic operation

Finally, with debug mode.
* `make -j USE_SDC=TRUE DEBUG=TRUE`
* `mpiexec -n 16 ./Maestro2d.gnu.DEBUG.MPI.SDC.ex inputs_2d_smallscale_sdc amr.max_level=1 maestro.eps_init_proj_cart = 1.e-9`
* I get Erroneous arithmetic operation before the first timestep

**Comment by ChrisDeGrendele** [comment]
Reacting bubble also fails before the first timestep, when run with SDC and `amr.max_level=1`

**Comment by ajnonaka** [comment]
The third case ("Finally, with debug mode.") fixed with PR #226
