### ISSUE TITLE
examples failing compilation

### ISSUE THREAD

**Issue by ajnonaka** [AMReX-Astro/MAESTROeX#299]
Each of these examples fails compilation on my workstation/laptop, each for seemingly different reasons:
fully_convective_star
test_advect - fixed with #300 
test_projection
test_react - fixed with #303 
xrb_mixed - fixed with #301 
wdconvect - fixed with #305

**Comment by zingale** [comment]
fully_convective_star is still using the old Fortran model parser in its heating, so that needs to be ported to the C++ version.

**Comment by ajnonaka** [comment]
For wdconvect, the USE_FORT_MICROPHYSICS:=TRUE should be removed.  Even so, ignition_chamulak is a problem, as ignition_simple does work.

**Comment by zingale** [comment]
`test_projection` needs to be converted to C++

**Comment by ajnonaka** [comment]
`test_react` needs to be converted to C++.  It is also using ignition_chamulak by default.

**Comment by zingale** [comment]
these have been fixed
