### ISSUE TITLE
Output Mach number in plot files

### ISSUE THREAD

**Issue by harpolea** [AMReX-Astro/MAESTROeX#31]
It would be useful for the plotfiles to include the Mach number

**Comment by zingale** [comment]
is there a reason MAESTROeX doesn't use the AMReX derive functionality?  Is that only available with StateData?

**Comment by asalmgren** [comment]
Yes that's an AmrLevel not AmrCore thing ...

**Comment by harpolea** [comment]
Implemented in 55c53944
