### ISSUE TITLE
fab.format affects both plotfiles and checkpoint files

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/MAESTROeX#315]
We sometimes use `fab.format = NATIVE_32` to write single-precision plotfiles, but it appears that this makes the checkpoint files output in single precision as well.  This is not how Castro behaves.  We should always write checkpoint files in double precision.

**Comment by zingale** [comment]
this was brought up in #314

**Comment by doreenfan** [comment]
Castro uses `AmrLevel::checkPoint()` to save the checkpoint files, which has the NATIVE format built-in, whereas MAESTROeX does not. 
PR #316 should fix this issue.
