### ISSUE TITLE
port unit tests

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/MAESTROeX#33]
The original MAESTRO had unit tests under the `Exec/` directory.  These had their own drivers.  We should port them to MAESTROeX

**Comment by harpolea** [comment]
I've ported over most of the unit tests from MAESTRO, however some of the unit tests do not work / report larger errors than expected:

- `test_advect` reports large errors 
- `test_average` seems to work
- `test_basestate` works for `planar`, however some of the other problems require spherical for `DIM<3` (which MAESTROeX does not support) or require networks that are not supported by `Microphysics` (e.g. `planar-invsq` requires `pphotcno`)
- `test_diffusion`'s errors are larger than expected
- `test_eos` seems to work for both gamma law and helmholtz EoS (though error in T(p,s) is a little high for helmholtz)
- `test_projection`: 2d periodic is ok (errors for the nodal solver are a little high, mac solver does well), 2d wall does not work (nodal solver does not converge, mac solver has relative error > 2). 3d periodic has pretty large errors, 3d wall also does not work
- `test_react`: some of the tests require networks that are not supported by `Microphysics`. Heating tests run, but segfaults for tests with burning.

**Comment by harpolea** [comment]
test_advect fixed in d4beb4aa48b8349e68c6733df38a02c2b29b6d4e
