### ISSUE TITLE
AmrCore vs Amr

### ISSUE THREAD

**Issue by tobyeh** [AMReX-Astro/MAESTROeX#36]
Are there any thoughts on moving the current version of MaestroeX to take advantage of the Amr/AmrLevel classes (like IAMR) rather than the current implementation using AmrCore? Is there any obvious advantage to doing this?

**Comment by zingale** [comment]
The main thing that the Amr/AmLevel classes get you is subcycling, but we've made the decision a long time ago that given the complexity of the Maestro algorithm, including base state evolution, we didn't want to do subcycling.  So without that need, the idea was that the AmrCore stuff is much simpler to deal with than StateData.  Others might have more opinions.
