### ISSUE TITLE
reacting_bubble fails when run on gpu

### ISSUE THREAD

**Issue by biboyd** [AMReX-Astro/MAESTROeX#401]
The reacting_bubble unit test fails when run with compiled with `USE_CUDA=TRUE`. Works fine using cpus. There appears to be an issue when initializing the base state.

Output:

~~~
Initializing AMReX (23.10-21-g152fdac6aa4c)...
MPI initialized with 1 MPI processes
MPI initialized with thread support level 0
Initializing CUDA...
CUDA initialized with 1 device.
AMReX (23.10-21-g152fdac6aa4c) initialized
Calling Setup()
Calling ReadParameters()
reading extern runtime parameters ...
Calling VariableSetup()
Calling BCSetup()
Calling BaseStateGeometry::Init()
Calling Init()
Calling InitData()
initdata model_File = model.hse.cool.coulomb
model file = model.hse.cool.coulomb


reading initial model
640 points found in the initial model
6 variables found in the initial model
model file mapping, level: 0
dr of MAESTRO base state =                            562500.000000
dr of input file data =                               562500.000000

maximum radius (cell-centered) of input model =       359718750.000000

Maximum HSE Error = -1000000000000000019884624838656.000000
(after putting initial model into base state arrays, and
for density < base_cutoff_density)

Segfault
~~~

To replicate, in the reacting_bubble directory:
~~~
make -j 4 USE_MPI=FALSE USE_OMP=FALSE USE_CUDA=TRUE DEBUG=TRUE
srun -n 1 Maestro3d.gnu.DEBUG.CUDA.ex inputs_3d_gpu_regression
~~~

I believe I have traced the issue to `BaseStateGeometry::Init` in `Source/BaseStateGeometry.cpp` where something goes wrong when `nr` and `dr` are set in lines 63-64

**Comment by zingale** [comment]
in particular, it looks like we are using `GPU::ManagedVector` a lot in `Basestate.H`, so we need to use the managed arena.

**Comment by biboyd** [comment]
Okay, running with `amrex.the_arena_is_managed=1`  fixes the main issue and the test initializes correctly now. 

However there is a new issue when we try to advance a timestep:

~~~
Timestep 0 starts with TIME = 0 DT = 0.0004741795139

Cell Count:
Level 0, 1327104 cells
inner sponge: r_sp      , r_tp      : 186468750, 224718750
<<< STEP 1 : react state >>>
<<< STEP 2 : make w0 >>>
<<< STEP 3 : create MAC velocities >>>
MLMG: Initial rhs               = 2728631.973
MLMG: Initial residual (resid0) = 2728631.973
MLMG: Final Iter. 1 resid, resid/bnorm = -1.797693135e+308, -6.588257971e+301
MLMG: Timers: Solve = 0.175576918 Iter = 0.145792589 Bottom = 0.00399682
<<< STEP 4 : advect base >>>
            :  density_advance >>>
            :   tracer_advance >>>
Erroneous arithmetic operation
See Backtrace.0 file for details
~~~

I'll look more into this, to see exactly where it is breaking

**Comment by ajnonaka** [comment]
Possible problem, but not sure.
After the first call to DensityAdvance in MaestroAdvance.cpp, if running with GPU and TEST=TRUE, the density field in "s2" is completely full of NaNs.
There might be a race condition - there are multiple ParallelFor's within the MFIter in UpdateScal() for the comp=FirstSpec case.  The first ParallelFor updates the species, the second one sums them up to form density.
If the GPU streams don't all close after the ParallelFor there is a race condition.  However I tried splitting this routine off into to MFIters and it still doesn't work.
Not even sure if there really is a race condition but the symptoms are there (this works fine on CPU...)

**Comment by ajnonaka** [comment]
Never mind, the NaNs appear in the first ParallelFor when computing snew for species *sigh* - back to the drawing board.

**Comment by ajnonaka** [comment]
I found it - there is a race condition in SlopeZ where near certain physical boundaries the code is using slopes computed in neighboring cells which haven't necessarily been computed yet if running on a gpu.  Interestingly SlopeX and SlopeY had already been fixed.  I'll work on a PR.

**Comment by ajnonaka** [comment]
@biboyd test it with https://github.com/AMReX-Astro/MAESTROeX/pull/402 this should fix it.

**Comment by biboyd** [comment]
Everything seems to work now, thanks for all the help!
