### ISSUE TITLE
Update docs for managing jobs

### ISSUE THREAD

**Issue by dwillcox** [AMReX-Astro/MAESTROeX#63]
The docs for managing jobs (from the original Maestro) point to the old Titan job scripts path and don't clarify that the restart flag is now `maestro.restart_file=[checkpoint file]`.

We should update this as well as add MAESTROeX specific job scripts.

The HPSS archiving script should also use the new C++ ftime in AMReX.

I'm testing these changes and will update the docs when I confirm they work.

**Comment by zingale** [comment]
this should all be cut out and switched over to the workflow repo

**Comment by dwillcox** [comment]
okay, I'll put the job scripts in https://github.com/AMReX-Astro/workflow/tree/master/job_scripts

Since Castro and MaestroEx need different restart flags, I'll check the executable name to set the restart flag properly.

**Comment by zingale** [comment]
this is all now at AMReX-Astro/workflow
