### ISSUE TITLE
burning_cutoff_density is too high by default

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/MAESTROeX#64]
The default value of `burning_cutoff_density` is 3.e6 (g/cc).  This reflects Maestro's origin as a code for modeling burning in WDs, but for other applications users may be unaware of this cutoff.  We should have this off by default (set it to 0.0 as in Castro).  This point of this parameter is optimization, just to skip the burn in regions where it shouldn't matter.

**Comment by ajnonaka** [comment]
One could make this argument for all the cutoff densities.  Perhaps we should force the user to set these by having the default be -1, and abort if it's not set in the inputs file.

**Comment by zingale** [comment]
I like that idea.

**Comment by ajnonaka** [comment]
There is `base_cutoff_density`, `anelastic_cutoff`, and `burning_cutoff_density` that should have this behavior.  (aesthetically we should call it `anelastic_cutoff_density` instead)  There is also a `buoyancy_cutoff_factor` but I think the default of 5 can be kept for that.

**Comment by ajnonaka** [comment]
In the original MAESTRO, the error checking to make sure the inputs files didn't have nonsensical values was in `probin.template`.  Wondering where to put the equivalent statements in MAESTROeX.  Maybe in `meth_params.template` at the end of `read_method_params`...?

**Comment by ajnonaka** [comment]
I'm thinking `base` and `anelastic` cutoff should be required in the inputs file.  `burning`, if not supplied, will be set to `base` (this is what original MAESTRO did).  Any objections? (it's easy to change later)

**Comment by harpolea** [comment]
Those sound good to me - they're the ones I had issues with for the massive star (in that I didn't realise that the cutoff parameters existed or that they were set to values that were so high for this problem).

**Comment by ajnonaka** [comment]
Implemented and merged in from cutoff_cleanup branch.

 renname anelastic_cutoff -> anelastic_cutoff_density

require anelastic and base_cutoff_density to be supplied in the inputs file - code aborts if not supplied

burning_cutoff_density takes on the value of base_cutoff_density if not supplied in the inputs file

all inputs files updated to retain the old defaults (3.e6) if nothing was supplied
