### ISSUE TITLE
have problem-specific parameters use the runtime parameter functionality

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/MAESTROeX#7]
Instead of manually adding problem-specific parametrers in a `probdata.f90`, and then setting the initial value in `probdata_init`, we should consider adding the parameters in an `_parameters` file, that is automatically captured by the build system.  This makes it easier to maintain and document.

**Comment by zingale** [comment]
e.g., this builds directly from how we do the microphysics runtime parameters

**Comment by ajnonaka** [comment]
Implemented by Alice.
