### ISSUE TITLE
summit pgi compiler reading namelist

### ISSUE THREAD

**Issue by ajnonaka** [AMReX-Astro/MAESTROeX#70]
When compiling/running on summit with pgi, an error message appears

```
 ERROR: problem in the namelist
FORTRAN STOP
```

You can compile/run with gnu and there's no error.  Or you can comment out the exit command and use pgi and it seems to run ok.  We suspect this is an issue due to combining the inputs file and probin (namelist) into 1 file.

**Comment by doreenfan** [comment]
Fixed with latest commit (390a0f8bc0d1da32f37acc1652999412a4745aa7) on new_nugpu branch.
