### ISSUE TITLE
Should we drop 1-d support

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/MAESTROeX#86]
Support for 1-d problems was added to original Maestro to allow us to model smallscale flames.  In the original Bell et al. 2004 low Mach algorithm we used for flames, we never had 1-d -- we just ran flames in long, narrow 2-d domains if we were just interested in the laminar properties.

1-d doesn't really make sense for atmospheric flows.

So I would propose that we remove 1-d support from MAESTROeX.  We can still do smallscale flames in 2-d if needed (and this is not any user's science priority at the moment).

**Comment by ajnonaka** [comment]
I am fine with eliminaing 1-d support.
