### ISSUE TITLE
Planar base state for GPU

### ISSUE THREAD

**Issue by ajnonaka** [AMReX-Astro/MAESTROeX#95]
Similar to what was done for spherical, we should map the base state onto full-D multifabs before passing into the fortran subroutines to avoid having huge base state copies on the GPU.

**Comment by harpolea** [comment]
This needs to be fixed for:
- [ ]  `MaestroForce.cpp/make_vel_force`, `modify_scal_force`, `modify_scal_force_sphr`, `mkrhohforce`
- [ ]  `MaestroGamma.cpp/make_gamma`
- [ ]  `MaestroRhoHT.cpp/makeTfromRhoH`,  `makeTfromRhoH`, `makeMachfromRhoH` & `makeCsfromRhoH`
- [ ]  `MaestroMakeS.cpp/make_S_cc`, `create_correction_delta_gamma1_term`, `make_rhcc_for_nodalproj`, `create_correction_cc`, `make_rhcc_for_macproj`
- [ ]   `MaestroAdvection.cpp/mkutrans_2d`, `mkutrans_3d`, `update_rhoh`, `update_velocity`, `update_velocity_sphr`
- [ ]  `MaestroDt.cpp/estdt`, `estdt_sphr`, `firstdt`
- [ ]  `MaestroPlot.cpp/make_magvel`, `make_deltagamma`, `make_divw0`

**Comment by zingale** [comment]
this appears to have been completed
